Eccube\Entity\ApiConfig:
    type: entity
    table: dtb_api_config
    repositoryClass: Eccube\Repository\ApiConfigRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: api_config_id
            generator:
                strategy: IDENTITY
    fields:
        operation_name:
            type: text
            nullable: false
        operation_description:
            type: text
            nullable: true
        auth_types:
            type: text
            nullable: false
        enable:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
        is_log:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
        sub_data:
            type: text
            nullable: true
        del_flg:
            type: smallint
            nullable: false
            unsigned: false
            default: '0'
        create_date:
            type: datetime
            nullable: false
            default: CURRENT_TIMESTAMP
        update_date:
            type: datetime
            nullable: false
            default: '0000-00-00 00:00:00'
    lifecycleCallbacks: {  }
