controllers:
    resource: ../../src/Eccube/Controller/
    type: annotation
customize_controllers:
    resource: ../../app/Customize/Controller/
    type: annotation

#    prefix: /{_locale}
    # prefix: /
    # requirements:
    #     _locale: '%app_locales%'
    # defaults:
    #     _locale: '%locale%'

# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/cookbook/templating/render_without_controller.html
# homepage:
#     path: /{_locale}
#     requirements:
#         _locale: '%app_locales%'
#     defaults:
#         _controller: FrameworkBundle:Template:template
#         template: default/homepage.html.twig
#         _locale: '%locale%'
admin_logout:
    path: '/%eccube_admin_route%/logout'
logout:
    path: /logout
