#before_commands:
#- "composer update --prefer-source"

tools:
    #external_code_coverage: true
    #php_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["build", "docs", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["build", "docs", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "docs", "tests", "vendor"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["src/*", "tests/*"]
    sensiolabs_security_checker: true
