version: "3"

services:
  zap:
    image: ghcr.io/ec-cube/zaproxy:0.1.0
    user: root
    # ENTRYPOINT を無効化
    entrypoint: ["sh", "-c"]
    # コンテナを待機させる
    command: ["tail -f /dev/null"]
    volumes:
      - ./zap/policies:/home/zap/.ZAP/policies/
      - ./zap:/zap/wrk/
    depends_on:
      - ec-cube
    networks:
      - backend
      - default
    tty: true
    healthcheck:
      test: echo 'zap'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s