version: '3'

volumes:
  mysql-database:
    driver: local

services:
  ec-cube:
    environment:
      DATABASE_URL: "mysql://dbuser:secret@mysql/eccubedb"
      DATABASE_SERVER_VERSION: 5.7
      DATABASE_CHARSET: 'utf8mb4'
      IGNORE_DATABASE_INITIALIZATION: 1

  mysql:
    build:
      context: .github/workflows/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eccubedb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-database:/var/lib/mysql
    ports:
      - '13306:3306'
    networks:
      - backend
