version: "3"

services:
  zap:
    image: ghcr.io/ec-cube/zaproxy:0.1.0
    command: sh -c "zap.sh -cmd -configfile /zap/wrk/options.properties -certpubdump /zap/wrk/owasp_zap_root_ca.cer && tail -f /dev/null"
    volumes:
      - ./zap/policies:/home/zap/.ZAP/policies/
      - ./zap:/zap/wrk/
    depends_on:
      - ec-cube
    networks:
      - backend
      - default
    tty: true
    healthcheck:
      test: echo 'zap'
      interval: 3s
      timeout: 3s
      retries: 3