<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Entity\BaseInfo;

/**
 * BaseInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends AbstractRepository<BaseInfo>
 */
class BaseInfoRepository extends AbstractRepository
{
    /**
     * BaseInfoRepository constructor.
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, BaseInfo::class);
    }

    /**
     * @return BaseInfo
     */
    public function get(int $id = 1): BaseInfo
    {
        $BaseInfo = $this->find($id);

        if (null === $BaseInfo) {
            throw new \Exception('BaseInfo not found. id = '.$id);
        }

        return $this->find($id);
    }
}
