<?php
/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) 2000-2015 LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{

    public function setApp($app)
    {
        $this->app = $app;
    }

    public function findOrCreate($block_id, $DeviceType)
    {

        if ($block_id == null) {
            return $this->newBlock($DeviceType);
        } else {
            return $this->getBlock($block_id, $DeviceType);
        }

    }

    public function newBlock($DeviceType)
    {
        $Block = new \Eccube\Entity\Block();
        $Block
            ->setDeviceType($DeviceType);
        $block_id = $this->getNewBlockId($DeviceType);
        $Block->setBlockId($block_id);
        $Block->setDeletableFlg(1);

        return $Block;
    }

    private function getNewBlockId($DeviceType)
    {

        $qb = $this->createQueryBuilder('b')
            ->select('max(b.id) +1 as block_id')
            ->where('b.DeviceType = :DeviceType')
            ->setParameter('DeviceType', $DeviceType);
        $result = $qb->getQuery()->getSingleResult();

        return $result['block_id'];

    }

    /**
     * ブロックの情報を取得.
     *
     * @param  integer $block_id       ブロックID
     * @param  \Eccube\Entity\Master\DeviceType $DeviceType
     * @return array
     */
    public function getBlock($block_id, $DeviceType)
    {
        $Block = $this->findOneBy(array(
            'id' => $block_id,
            'DeviceType' => $DeviceType,
        ));

        return $Block;
    }

    /**
     * ブロック一覧の取得.
     *
     * @param  \Eccube\Entity\Master\DeviceType $DeviceType
     * @return array
     */
    public function getList($DeviceType)
    {
        $qb = $this->createQueryBuilder('b')
            ->orderBy('b.block_id', 'DESC')
            ->where('b.DeviceType = :DeviceType')
            ->setParameter('DeviceType', $DeviceType)
        ;

        $Blocks = $qb
            ->getQuery()
            ->getResult();

        return $Blocks;
    }
}
