<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Entity\Block;
use Eccube\Entity\BlockPosition;
use Eccube\Entity\Layout;
use Eccube\Util\IdUtil;

/**
 * BlockPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends AbstractRepository<BlockPosition>
 */
class BlockPositionRepository extends AbstractRepository
{
    /**
     * BlockPositionRepository constructor.
     */
    public function __construct(protected BlockRepository $blockRepository, RegistryInterface $registry)
    {
        parent::__construct($registry, BlockPosition::class);
    }

    /**
     * レイアウトに紐づくブロックの個数分登録を行う
     *
     * @param  array<mixed>|null $data
     * @param  Block[] $Blocks
     * @param  Block[]|null $UnusedBlocks
     */
    public function register(?array $data, array $Blocks, ?array $UnusedBlocks, ?Layout $Layout): void
    {
        $em = $this->getEntityManager();

        $registered = [];
        $max = count($Blocks) + count((array) $UnusedBlocks);
        for ($i = 0; $i < $max; $i++) {
            // block_idが取得できない場合はinsertしない
            if (!isset($data['block_id_'.$i])) {
                continue;
            }
            $blockId = IdUtil::toId($data['block_id_'.$i]);
            $section = IdUtil::toId($data['section_'.$i] ?? null);
            $blockRow = isset($data['block_row_'.$i]) ? IdUtil::toId($data['block_row_'.$i]) : null;
            // 値が整数でない場合はinsertしない
            if (null === $blockId || null === $section || (isset($data['block_row_'.$i]) && null === $blockRow)) {
                continue;
            }
            // 未使用ブロックはinsertしない
            if ($section === Layout::TARGET_ID_UNUSED) {
                continue;
            }
            // 同じ配置への重複はinsertしない
            if (isset($registered[$section][$blockId])) {
                continue;
            }
            $Block = $this->blockRepository->find($blockId);
            if (null === $Block) {
                continue;
            }
            $registered[$section][$blockId] = true;
            $BlockPosition = new BlockPosition();
            $BlockPosition
                ->setBlockId($blockId)
                ->setLayoutId($Layout->getId())
                ->setBlockRow($blockRow)
                ->setSection($section)
                ->setBlock($Block)
                ->setLayout($Layout);
            $Layout->addBlockPosition($BlockPosition);
            $em->persist($BlockPosition);
            $em->flush();
        }
    }
}
