<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\ORM\NoResultException;
use Eccube\Entity\Calendar;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends AbstractRepository
{
    /**
     * CalendarRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Calendar::class);
    }

    /**
     * @param int $id
     *
     * @return Calendar
     */
    public function get($id = 1)
    {
        $calendar = $this->find($id);

        if (null === $calendar) {
            throw new \Exception('Calendar not found. id = '.$id);
        }

        return $this->find($id);
    }

    /**
     * getList
     *
     * @return array|null
     */
    public function getList()
    {
        $qb = $this->createQueryBuilder('c')
            ->orderBy('c.id', 'DESC')
            //->where('t.Product IS NULL AND t.ProductClass IS NULL')
        ;
        $Calendars = $qb
            ->getQuery()
            ->getResult();

        return $Calendars;
    }

    /**
     * delete.
     *
     * @param  int|\Eccube\Entity\Calend $Calendar
     *
     * @throws NoResultException
     */
    public function delete($Calendar)
    {
        if (!$Calendar instanceof Calendar) {
            $Calendar = $this->find($Calendar);
        }
        if (!$Calendar) {
            throw new NoResultException();
        }
        $em = $this->getEntityManager();
        $em->remove($Calendar);
        $em->flush();
    }

    /**
     * Calendar のキャッシュをクリアする.
     *
     * getByRule() をコールすると、結果をキャッシュし、2回目以降はデータベースへアクセスしない.
     * このメソッドをコールすると、キャッシュをクリアし、再度データベースを参照して結果を取得する.
     */
    public function clearCache()
    {
        $this->rules = [];
    }
}
