<?php
/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) 2000-2015 LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


namespace Eccube\Repository;

use Doctrine\DBAL\Exception\DriverException;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Eccube\Annotation\Repository;
use Eccube\Entity\ClassCategory;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ClasscategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @Repository
 */
class ClassCategoryRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, ClassCategory::class);
    }

    /**
     * 規格カテゴリの一覧を取得します.
     *
     * @param \Eccube\Entity\ClassName $ClassName 検索対象の規格名オブジェクト. 指定しない場合は、すべての規格を対象に取得します.
     * @return array 規格カテゴリの配列
     */
    public function getList(\Eccube\Entity\ClassName $ClassName = null)
    {
        $qb = $this->createQueryBuilder('cc')
            ->orderBy('cc.rank', 'DESC'); // TODO ClassName ごとにソートした方が良いかも
        if ($ClassName) {
            $qb->where('cc.ClassName = :ClassName')->setParameter('ClassName', $ClassName);
        }
        $ClassCategories = $qb->getQuery()
            ->getResult();

        return $ClassCategories;
    }

    /**
     * 規格カテゴリを登録します.
     *
     * @param $ClassCategory
     */
    public function save($ClassCategory)
    {
        if (!$ClassCategory->getId()) {
            $ClassName = $ClassCategory->getClassName();
            $rank = $this->createQueryBuilder('cc')
                ->select('COALESCE(MAX(cc.rank), 0)')
                ->where('cc.ClassName = :ClassName')
                ->setParameter('ClassName', $ClassName)
                ->getQuery()
                ->getSingleScalarResult();

            $ClassCategory->setRank($rank + 1);
            $ClassCategory->setVisible(true);
        }

        $em = $this->getEntityManager();
        $em->persist($ClassCategory);
        $em->flush($ClassCategory);
    }

    /**
     * 規格カテゴリを削除する.
     *
     * @param ClassCategory $ClassCategory
     *
     * @throws ForeignKeyConstraintViolationException 外部キー制約違反の場合
     * @throws DriverException SQLiteの場合, 外部キー制約違反が発生すると, DriverExceptionをthrowします.
     */
    public function delete($ClassCategory)
    {
        $this->createQueryBuilder('cc')
            ->update()
            ->set('cc.rank', 'cc.rank - 1')
            ->where('cc.rank > :rank AND cc.ClassName = :ClassName')
            ->setParameter('rank', $ClassCategory->getRank())
            ->setParameter('ClassName', $ClassCategory->getClassName())
            ->getQuery()
            ->execute();

        $em = $this->getEntityManager();
        $em->remove($ClassCategory);
        $em->flush($ClassCategory);
    }

    /**
     * 規格カテゴリの表示/非表示を切り替える.
     *
     * @param $ClassCategory
     */
    public function toggleVisibility($ClassCategory)
    {
        if ($ClassCategory->isVisible()) {
            $ClassCategory->setVisible(false);
        } else {
            $ClassCategory->setVisible(true);
        }

        $em = $this->getEntityManager();
        $em->persist($ClassCategory);
        $em->flush($ClassCategory);
    }
}
