<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CsvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CsvRepository extends EntityRepository
{
}
