<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
    public $app;

    public function setApplication($app)
    {
        $this->app = $app;
    }

    public function newCustomer()
    {
        $customer = new \Eccube\Entity\Customer();

        $customer->setCreateDate(new \DateTime())
            ->setUpdateDate(new \DateTime())
            ->setPoint(0)
            ->setStatus(1)
            ->setDelFlg(0);

        return $customer;
    }

}
