<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DelivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelivRepository extends EntityRepository
{
    public function findOrCreate($id)
    {
        if ($id == 0) {
            $Creator = $this
                ->getEntityManager()
                ->getRepository('\Eccube\Entity\Member')
                ->find(2);

            $rank = $this
                ->findOneBy(array(), array('rank' => 'DESC'))
                ->getRank() + 1;

            $Deliv = new \Eccube\Entity\Deliv();
            $Deliv
                ->setRank($rank)
                ->setStatus(1)
                ->setDelFlg(0)
                ->setCreator($Creator)
                ->setProductTypeId(1)
            ;

        } else {
            $Deliv = $this->find($id);

        }

        return $Deliv;
    }
}
