<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DelivTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DelivTimeRepository extends EntityRepository
{
}
