<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MailmagaTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailmagaTemplateRepository extends EntityRepository
{
}
