<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MailtemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailtemplateRepository extends EntityRepository
{
    public function findOrCreate($id)
    {
        if ($id == 0) {
            $Creator = $this
                ->getEntityManager()
                ->getRepository('\Eccube\Entity\Member')
                ->find(2);

            $Mailtemplate = new \Eccube\Entity\Mailtemplate();
            $Mailtemplate
                ->setDelFlg(0)
                ->setCreator($Creator)
            ;

        } else {
            $Mailtemplate = $this->find($id);

        }

        return $Mailtemplate;
    }
}
