<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakerRepository extends EntityRepository
{
}
