<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Entity\OrderDisplaySetting;

/**
 * OrderDisplaySettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends AbstractRepository<OrderDisplaySetting>
 */
class OrderDisplaySettingRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, OrderDisplaySetting::class);
    }

    /**
     * 表示項目設定を取得（有効な項目のみ・ソート順）.
     *
     * @return array<OrderDisplaySetting>
     */
    public function getEnabledSettings(): array
    {
        return $this->createQueryBuilder('o')
            ->where('o.enabled = :enabled')
            ->setParameter('enabled', true)
            ->orderBy('o.sort_no', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * 全表示項目設定を取得（ソート順）.
     *
     * @return array<OrderDisplaySetting>
     */
    public function getAllSettings(): array
    {
        return $this->createQueryBuilder('o')
            ->orderBy('o.sort_no', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * フィールド名で設定を取得.
     */
    public function findByFieldName(string $fieldName): ?OrderDisplaySetting
    {
        return $this->findOneBy(['field_name' => $fieldName]);
    }

    /**
     * 表示項目設定を保存.
     *
     * @param array<array<string, mixed>> $settings
     */
    public function saveSettings(array $settings): void
    {
        $em = $this->getEntityManager();

        foreach ($settings as $settingData) {
            // 必須フィールドの存在確認
            if (!isset($settingData['field_name']) || !isset($settingData['disp_name'])) {
                continue; // 必須フィールドが不足している場合はスキップ
            }

            $setting = $this->findByFieldName($settingData['field_name']);
            if (!$setting) {
                $setting = new OrderDisplaySetting();
            }

            $setting->setFieldName($settingData['field_name']);
            $setting->setDispName($settingData['disp_name']);

            // デフォルト値の設定
            $enabled = $settingData['enabled'] ?? true;
            $sortNo = $settingData['sort_no'] ?? 0;

            // 型変換とバリデーション
            if (is_string($enabled)) {
                $enabled = filter_var($enabled, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
                if ($enabled === null) {
                    $enabled = true; // デフォルト値
                }
            }

            if (is_string($sortNo)) {
                $sortNo = (int) $sortNo;
            }

            $setting->setEnabled($enabled);
            $setting->setSortNo($sortNo);

            // タイムスタンプは SaveEventSubscriber が自動設定する
            $em->persist($setting);
        }

        $em->flush();
    }

    /**
     * 新しいエンティティを作成.
     */
    public function newEntity(): OrderDisplaySetting
    {
        // タイムスタンプは SaveEventSubscriber が persist 時に自動設定する
        return new OrderDisplaySetting();
    }
}
