<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrefRepository extends EntityRepository
{
    public function findMasterData()
    {
        $results = $this->getEntityManager()
            ->createQuery('SELECT p FROM Eccube\Entity\Pref p ORDER BY p.rank ASC')
            ->getResult();

        $pref[''] = null;

        foreach($results as $res) {
            $pref[$res->getId()] = $res->getName();
        }

        return $pref;
    }

}
