<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductClassRepository extends EntityRepository
{
}
