<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RecommendProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecommendProductRepository extends EntityRepository
{

    protected $app;

    public function setApp($app)
    {
        $this->app = $app;
    }

    public function getList()
    {
        $Products = $this
            ->findBy(
                array(),
                array('rank' => 'ASC'),
                $this->app['config']['recommend_num'],
                0
            )
        ;
        return $Products;
    }
}
