<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SendHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SendHistoryRepository extends EntityRepository
{
}
