<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShippingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingRepository extends EntityRepository
{
}
