<?php

namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaxRuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRuleRepository extends EntityRepository
{
}
