<?php

namespace Eccube\Tests\Web\Admin\Setting\Shop;

use Eccube\Tests\Web\Admin\AbstractAdminWebTestCase;

class TradeLawControllerTest extends AbstractAdminWebTestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testValidationName() {

    }

    public function testValidationDescription() {

    }

    public function testUpdate() {

    }
}
