<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150716110834 extends AbstractMigration
{

    const NAME = 'dtb_csv';

    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        if (!$schema->hasTable(self::NAME)) {
            return true;
        }

        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'id', NULL, '商品ID', 1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'Status', 'id', '公開ステータス(ID)', 2, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'Status', 'name', '公開ステータス(名称)', 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'name', NULL, '商品名', 4, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'note', NULL, 'ショップ用メモ欄', 5, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'description_list', NULL, '商品説明(一覧)', 6, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'description_detail', NULL, '商品説明(詳細)', 7, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'search_word', NULL, '検索ワード', 8, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'free_area', NULL, 'フリーエリア', 9, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'id', NULL, '商品規格ID', 10, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'ProductType', 'id', '商品種別(ID)', 11, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'ProductType', 'name', '商品種別(名称)', 12, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'ClassCategory1', 'id', '規格分類1(ID)', 13, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'ClassCategory1', 'name', '規格分類1(名称)', 14, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'ClassCategory2', 'id', '規格分類2(ID)', 15, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'ClassCategory2', 'name', '規格分類2(名称)', 16, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'DeliveryDate', 'id', '発送日目安(ID)', 17, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'DeliveryDate', 'name', '発送日目安(名称)', 18, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'code', NULL, '商品コード', 19, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'stock', NULL, '在庫数', 20, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'stock_unlimited', NULL, '在庫数無制限フラグ', 21, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'sale_limit', NULL, '販売制限数', 22, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'price01', NULL, '通常価格', 23, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'price02', NULL, '販売価格', 24, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'delivery_fee', NULL, '送料', 25, 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\Product', 'ProductImage', 'file_name', '商品画像', 26, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'ProductType', 'id', '商品カテゴリ(ID)', 27, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (1, 'Eccube\\\\Entity\\\\ProductClass', 'ProductType', 'name', '商品カテゴリ(名称)', 28, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'id', NULL, '会員ID',  1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'name01', NULL, 'お名前(姓)',  2, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'name02', NULL, 'お名前(名)',  3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'kana01', NULL, 'お名前(セイ)',  4, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'kana02', NULL, 'お名前(メイ)',  5, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'company_name', NULL, '会社名',  6, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'zip01', NULL, '郵便番号1',  7, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'zip02', NULL, '郵便番号2',  8, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'Pref', 'id', '都道府県(ID)',  9, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'Pref', 'name', '都道府県(名称)',  10, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'addr01', NULL, '住所1',  11, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'addr02', NULL, '住所2',  12, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'email', NULL, 'メールアドレス',  13, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'tel01', NULL, 'TEL1',  14, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'tel02', NULL, 'TEL2',  15, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'tel03', NULL, 'TEL3',  16, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'fax01', NULL, 'FAX1',  17, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'fax02', NULL, 'FAX2',  18, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'fax03', NULL, 'FAX3',  19, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'Sex', 'id', '性別(ID)',  20, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'Sex', 'name', '性別(名称)',  21, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'Job', 'id', '職業(ID)',  22, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'Job', 'name', '職業(名称)',  23, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'birth', NULL, '誕生日',  24, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'first_buy_date', NULL, '初回購入日',  25, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'last_buy_date', NULL, '最終購入日',  26, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'buy_times', NULL, '購入回数',  27, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'note', NULL, 'ショップ用メモ欄',  28, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'Status', 'id', '会員ステータス(ID)',  29, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'Status', 'name', '会員ステータス(名称)',  30, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'create_date', NULL, '登録日',  31, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (2, 'Eccube\\\\Entity\\\\Customer', 'update_date', NULL, '更新日',  32, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'id', NULL, '注文ID', 1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'Customer', 'id', '会員ID', 2, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'name01', NULL, 'お名前(姓)', 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'name02', NULL, 'お名前(名)', 4, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'kana01', NULL, 'お名前(セイ)', 5, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'kana02', NULL, 'お名前(メイ)', 6, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'company_name', NULL, '会社名', 7, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'zip01', NULL, '郵便番号1', 8, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'zip02', NULL, '郵便番号2', 9, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'Pref', 'id', '都道府県(ID)', 10, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'Pref', 'name', '都道府県(名称)', 11, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'addr01', NULL, '住所1', 12, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'addr02', NULL, '住所2', 13, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'email', NULL, 'メールアドレス', 14, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'tel01', NULL, 'TEL1', 15, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'tel02', NULL, 'TEL2', 16, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'tel03', NULL, 'TEL3', 17, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'fax01', NULL, 'FAX1', 18, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'fax02', NULL, 'FAX2', 19, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'fax03', NULL, 'FAX3', 20, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'Sex', 'id', '性別(ID)', 21, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'Sex', 'name', '性別(名称)', 22, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'Job', 'id', '職業(ID)', 23, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'Job', 'name', '職業(名称)', 24, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'birth', NULL, '誕生日', 25, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'note', NULL, 'ショップ用メモ欄', 26, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'subtotal', NULL, '小計', 27, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'discount', NULL, '値引き', 28, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'delivery_fee_total', NULL, '送料', 29, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'tax', NULL, '税金', 30, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'total', NULL, '合計', 31, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'payment_total', NULL, '支払合計', 32, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'OrderStatus', 'id', '対応状況(ID)', 33, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'OrderStatus', 'name', '対応状況(名称)', 34, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'Payment', 'id', '支払方法(ID)', 35, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'payment_method', NULL, '支払方法(名称)', 36, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'order_date', NULL, '受注日', 37, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'payment_date', NULL, '入金日', 38, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\Order', 'commit_date', NULL, '発送日', 39, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'id', NULL, '注文詳細ID', 40, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'Product', 'id', '商品ID', 41, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'ProductClass', 'id', '商品規格ID', 42, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'product_name', NULL, '商品名', 43, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'product_code', NULL, '商品コード', 44, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'class_name1', NULL, '規格名1', 45, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'class_name2', NULL, '規格名2', 46, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'class_category_name1', NULL, '規格分類名1', 47, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'class_category_name2', NULL, '規格分類名2', 48, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'price', NULL, '価格', 49, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'quantity', NULL, '個数', 50, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'tax_rate', NULL, '税率', 51, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (3, 'Eccube\\\\Entity\\\\OrderDetail', 'tax_rule', NULL, '税率ルール(ID)', 52, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'id', NULL, '注文ID', 1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'Customer', 'id', '会員ID', 2, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'name01', NULL, 'お名前(姓)', 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'name02', NULL, 'お名前(名)', 4, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'kana01', NULL, 'お名前(セイ)', 5, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'kana02', NULL, 'お名前(メイ)', 6, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'company_name', NULL, '会社名', 7, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'zip01', NULL, '郵便番号1', 8, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'zip02', NULL, '郵便番号2', 9, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'Pref', 'id', '都道府県(ID)', 10, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'Pref', 'name', '都道府県(名称)', 11, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'addr01', NULL, '住所1', 12, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'addr02', NULL, '住所2', 13, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'email', NULL, 'メールアドレス', 14, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'tel01', NULL, 'TEL1', 15, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'tel02', NULL, 'TEL2', 16, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'tel03', NULL, 'TEL3', 17, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'fax01', NULL, 'FAX1', 18, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'fax02', NULL, 'FAX2', 19, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'fax03', NULL, 'FAX3', 20, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'Sex', 'id', '性別(ID)', 21, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'Sex', 'name', '性別(名称)', 22, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'Job', 'id', '職業(ID)', 23, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'Job', 'name', '職業(名称)', 24, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'birth', NULL, '誕生日', 25, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'note', NULL, 'ショップ用メモ欄', 26, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'subtotal', NULL, '小計', 27, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'discount', NULL, '値引き', 28, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'delivery_fee_total', NULL, '送料', 29, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'tax', NULL, '税金', 30, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'total', NULL, '合計', 31, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'payment_total', NULL, '支払合計', 32, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'OrderStatus', 'id', '対応状況(ID)', 33, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'OrderStatus', 'name', '対応状況(名称)', 34, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'Payment', 'id', '支払方法(ID)', 35, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'payment_method', NULL, '支払方法(名称)', 36, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'order_date', NULL, '受注日', 37, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'payment_date', NULL, '入金日', 38, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Order', 'commit_date', NULL, '発送日', 39, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'id', NULL, '配送ID', 40, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'name01', NULL, '配送先_お名前(姓)', 41, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'name02', NULL, '配送先_お名前(名)', 42, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'kana01', NULL, '配送先_お名前(セイ)', 43, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'kana02', NULL, '配送先_お名前(メイ)', 44, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'company_name', NULL, '配送先_会社名', 45, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'zip01', NULL, '配送先_郵便番号1', 46, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'zip02', NULL, '配送先_郵便番号2', 47, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'Pref', 'id', '配送先_都道府県(ID)', 48, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'Pref', 'name', '配送先_都道府県(名称)', 49, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'addr01', NULL, '配送先_住所1', 50, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'addr02', NULL, '配送先_住所2', 51, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'tel01', NULL, '配送先_TEL1', 52, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'tel02', NULL, '配送先_TEL2', 53, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'tel03', NULL, '配送先_TEL3', 54, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'fax01', NULL, '配送先_FAX1', 55, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'fax02', NULL, '配送先_FAX2', 56, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'fax03', NULL, '配送先_FAX3', 57, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'Delivery', 'id', '配送業者(ID)', 58, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'shipping_delivery_name', NULL, '配送業者(名称)', 59, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'DeliveryTime', 'id', 'お届け時間ID', 60, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'shipping_delivery_time', NULL, 'お届け時間(名称)', 61, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'shipping_delivery_date', NULL, 'お届け希望日', 62, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'DeliveryFee', 'id', '送料ID', 63, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'shipping_delivery_fee', NULL, '送料', 64, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\Shipping', 'shipping_commit_date', NULL, '発送日', 65, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'id', NULL, '配送商品ID', 66, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'Product', 'id', '商品ID', 67, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'ProductClass', 'id', '商品規格ID', 68, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'product_name', NULL, '商品名', 69, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'product_code', NULL, '商品コード', 70, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'class_name1', NULL, '規格名1', 71, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'class_name2', NULL, '規格名2', 72, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'class_category_name1', NULL, '規格分類名1', 73, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'class_category_name2', NULL, '規格分類名2', 74, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'price', NULL, '価格', 75, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (4, 'Eccube\\\\Entity\\\\ShipmentItem', 'quantity', NULL, '個数', 76, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (5, 'Eccube\\\\Entity\\\\Category', 'id', NULL, 'カテゴリID', 1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (5, 'Eccube\\\\Entity\\\\Category', 'rank', NULL, '表示ランク', 2, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (5, 'Eccube\\\\Entity\\\\Category', 'name', NULL, 'カテゴリ名', 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (5, 'Eccube\\\\Entity\\\\Category', 'Parent', 'id', '親カテゴリID', 4, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");
        $this->addSql("INSERT INTO dtb_csv (csv_type, entity_name, field_name, reference_field_name, disp_name, rank, enable_flg, creator_id, create_date, update_date) VALUES (5, 'Eccube\\\\Entity\\\\Category', 'level', NULL, '階層', 5, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)");

    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DELETE FROM ' . self::NAME);

    }
}
