<?php
/*
 * Copyright © 2000-2006 LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 */
$arrPageList = array(
	1 => "TOPページ",
	2 => "ファッション",
	3 => "雑貨",
	4 => "家電",
	5 => "PC・周辺機器",
	6 => "美容・健康",
	7 => "食品",
	8 => "TVショッピング"
);

$arrPageTpl = array(
	1 => "index.tpl",
	2 => "products_list-c2.tpl",
	3 => "products_list-c3.tpl",
	4 => "products_list-c4.tpl",
	5 => "products_list-c5.tpl",
	6 => "products_list-c6.tpl",
	7 => "products_list-c7.tpl",
	8 => "products_list-c8.tpl",	
);

$arrPageURL = array(
	1 => "/index.php?",
	2 => "/products/list-c2.html&",
	3 => "/products/list-c3.html&",
	4 => "/products/list-c4.html&",
	5 => "/products/list-c5.html&",
	6 => "/products/list-c6.html&",
	7 => "/products/list-c7.html&",
	8 => "/products/list-c8.html&",
);


?>