# https://github.com/symfony/demo/blob/master/config/packages/prod/doctrine.yaml
# https://symfony.com/doc/master/bundles/DoctrineBundle/configuration.html
doctrine:
    orm:
        metadata_cache_driver:
            type: pool
            pool: doctrine.app_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.app_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.app_cache_pool
        second_level_cache:
            region_cache_driver:
                type: pool
                pool: doctrine.app_cache_pool

framework:
    cache:
        pools:
            doctrine.app_cache_pool:
                adapter: cache.app
