runs:
  using: "Composite"
  steps:
    - name: Get Composer Cache Directory
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306  # v5
      id: composer-cache
      with:
        path: ${{ github.workspace }}/vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: composer install
      run: composer install --dev --no-interaction -o --apcu-autoloader
      shell: bash
