# https://github.com/symfony/demo/blob/master/config/packages/prod/doctrine.yaml
# https://symfony.com/doc/master/bundles/DoctrineBundle/configuration.html
doctrine:
    orm:
        metadata_cache_driver:
            type: service
            id: doctrine.app_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.app_cache_provider
        result_cache_driver:
            type: service
            id: doctrine.app_cache_provider
        second_level_cache:
            region_cache_driver:
                type: service
                id: doctrine.app_cache_provider

services:
    doctrine.app_cache_provider:
        class: Doctrine\Common\Cache\Psr6\DoctrineProvider
        factory: ['Doctrine\Common\Cache\Psr6\DoctrineProvider', wrap]
        public: false
        arguments:
            - '@doctrine.app_cache_pool'

framework:
    cache:
        pools:
            doctrine.app_cache_pool:
                adapter: cache.app
