#!/usr/bin/env php
<?php
#require_once("vendor/autoload.php");
(@include_once __DIR__ . '/../vendor/autoload.php') || @include_once __DIR__ . '/../../../autoload.php';


set_time_limit(0);

$app = new Eccube\ConsoleApplication();

$console = &$app["console"];
$console->add(new Eccube\Command\RouterCommand(new Eccube\Application()));
$console->add(new Eccube\Command\CacheClearCommand(new Eccube\Application()));

$console->run();
