#!/usr/bin/env php
<?php
require_once("vendor/autoload.php");

set_time_limit(0);

#$app = new Eccube\Application();
$app = new Eccube\ConsoleApplication();

$console = &$app["console"];

$console->run();
