modules:
    config:
        WebDriver:
            host: '127.0.0.1'
            port: 9515
            url: 'http://127.0.0.1'
            browser: chrome
            capabilities:
                chromeOptions:
                    args: ["--headless", "--disable-gpu", "--no-sandbox", "--disable-dev-shm-usage", "--disable-setuid-sandbox"]
                    prefs:
                        download.default_directory: '%PWD%/codeception/_support/_downloads'
