<?php
    define ('ECCUBE_INSTALL', 'ON');
    define ('ROOT_DIR', '/home/web/naka.lockon.co.jp/');
    define ('SITE_URL', 'http://naka.lockon.co.jp/');
    define ('SSL_URL', 'http://naka.lockon.co.jp/');
    define ('DOMAIN_NAME', '.lockon.co.jp');
    define ('DB_USER', 'eccube_db_user');
    define ('DB_PASSWORD', 'password');
    define ('DB_SERVER', '127.0.0.1');
    define ('DB_NAME', 'eccube_db');
?>