<?php
    define ('ECCUBE_INSTALL', 'ON');
    define ('ROOT_DIR', '/home/web/test.ec-cube.net/');
    define ('SITE_URL', 'http://test.ec-cube.net/');
    define ('SSL_URL', 'http://test.ec-cube.net/');
    define ('DOMAIN_NAME', '.ec-cube.net');
    define ('DB_USER', 'eccube_db_user');
    define ('DB_PASSWORD', 'password');
    define ('DB_SERVER', 'naka.lockon.co.jp');
    define ('DB_NAME', 'eccube_db');	
?>