Eccube\Entity\ProductListMax:
    type: entity
    table: mtb_product_list_max
    repositoryClass: Eccube\Repository\ProductListMaxRepository
    fields:
        id:
            type: smallint
            id: true
            generator:
                strategy: AUTO
        name:
            type: text
        rank:
            type: smallint
    lifecycleCallbacks: {  }
