Eccube\Entity\ProductClass:
    type: entity
    table: dtb_products_class
    repositoryClass: Eccube\Repository\ProductClassRepository
    fields:
        id:
            type: integer
            column: product_class_id
            length: 11
            id: true
            generator:
                strategy: AUTO
        product_id:
            type: integer
        class_combination_id:
            type: integer
        product_type_id:
            type: integer
        product_code:
            type: text
        stock:
            type: decimal
            precision: 10
            scale: 0
        stock_unlimited:
            type: smallint
        sale_limit:
            type: decimal
            precision: 10
            scale: 0
        price01:
            type: decimal
            precision: 10
            scale: 0
        price02:
            type: decimal
            precision: 10
            scale: 0
        deliv_fee:
            type: decimal
            precision: 10
            scale: 0
        point_rate:
            type: decimal
            precision: 10
            scale: 0
        creator_id:
            type: integer
        create_date:
            type: datetime
        update_date:
            type: datetime
        down_filename:
            type: text
        down_realfilename:
            type: text
        del_flg:
            type: smallint
    manyToOne:
        Product:
            targetEntity: Eccube\Entity\Product
            inversedBy: ProductClasses
            joinColumn:
                name: product_id
                referencedColumnName: product_id
        ClassCombination:
            targetEntity: Eccube\Entity\ClassCombination
            inversedBy: ProductClasses
            joinColumn:
                name: class_combination_id
                referencedColumnName: class_combination_id
        ProductType:
            targetEntity: Eccube\Entity\ProductType
            inversedBy: ProductClasses
            joinColumn:
                name: product_type_id
                referencedColumnName: id
        Creator:
            targetEntity: Eccube\Entity\Member
            inversedBy: ProductClasses
            joinColumn:
                name: creator_id
                referencedColumnName: member_id
    lifecycleCallbacks:
        prePersist: [ setCreateDateAuto ]
        preUpdate:  [ setUpdateDateAuto ]
