<?php
    define ('ECCUBE_INSTALL', 'ON');
    define ('HTML_PATH', '/home/web/beta.ec-cube.net/html/');
    define ('SITE_URL', 'http://beta.ec-cube.net/');
    define ('SSL_URL', 'http://beta.ec-cube.net/');
    define ('URL_DIR', '/');
    define ('DOMAIN_NAME', '');
    define ('DB_TYPE', 'mysql');
    define ('DB_USER', 'eccube_db_user');
    define ('DB_PASSWORD', 'password');
    define ('DB_SERVER', '210.188.212.165');
    define ('DB_NAME', 'eccube_db');
    define ('DB_PORT', '3308');
    define ('DATA_PATH', '/home/web/beta.ec-cube.net/html/../data/');
?>