<?php
    define ('ECCUBE_INSTALL', 'ON');
    define ('HTML_PATH', 'C:\eclipse\workspace\dev.ec-cube.net\html/');
    define ('SITE_URL', 'http://localhost/eccube/');
    define ('SSL_URL', 'http://localhost/eccube/');
    define ('URL_DIR', '/eccube/');
    define ('DOMAIN_NAME', '');
    define ('DB_TYPE', 'mysql');
    define ('DB_USER', 'eccube');
    define ('DB_PASSWORD', 'eccube');
    define ('DB_SERVER', '127.0.0.1');
    define ('DB_NAME', 'eccube');
    define ('DB_PORT', '');
    define ('DATA_PATH', 'C:\eclipse\workspace\dev.ec-cube.net\html/../data/');
?>