<?php
    define ('ECCUBE_INSTALL', 'ON');
    define ('HTML_PATH', '/home/web/mobile.ec-cube.net/html/mobile/');
    define ('PC_HTML_PATH', '/home/web/mobile.ec-cube.net/html/');
    define ('SITE_URL', 'http://mobile.ec-cube.net/mobile/');
    define ('PC_SITE_URL', 'http://mobile.ec-cube.net/');
    define ('SSL_URL', 'http://mobile.ec-cube.net/mobile/');
    define ('PC_SSL_URL', 'http://mobile.ec-cube.net/');
    define ('URL_DIR', '/mobile/');
    define ('PC_URL_DIR', '/');
    define ('DOMAIN_NAME', '');
    define ('DB_TYPE', 'mysql');
    define ('DB_USER', 'mobile_db_user');
    define ('DB_PASSWORD', 'password');
    define ('DB_SERVER', '127.0.0.1');
    define ('DB_NAME', 'mobile_db');
    define ('DB_PORT', '3307');
    define ('DATA_PATH', '/home/web/mobile.ec-cube.net/html/../data/');
?>
