<?php

namespace Eccube\Repository\Master;

use Doctrine\ORM\EntityRepository;

/**
 * AllowedTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllowedTagRepository extends EntityRepository
{
}
