<?php

namespace Eccube\Repository\Master;

use Doctrine\ORM\EntityRepository;

/**
 * MobileDomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MobileDomainRepository extends EntityRepository
{
}
