<?php

namespace Eccube\Repository\Master;

/**
 * OrderItemTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
