<?php

namespace Eccube\Repository\Master;

use Eccube\Annotation\Repository;
use Eccube\Entity\Master\TaxDisplayType;
use Eccube\Repository\AbstractRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * TaxDisplayTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @Repository
 */
class TaxDisplayTypeRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, TaxDisplayType::class);
    }
}
