<?php

namespace Eccube\Repository\Master;

use Eccube\Annotation\Repository;
use Eccube\Repository\AbstractRepository;

/**
 * TaxTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @Repository
 */
class TaxTypeRepository extends AbstractRepository
{
}
