<?php

namespace Eccube\Repository\Master;

/**
 * TaxTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
