services:
  Eccube\Tests\Fixture\Generator:
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@security.user_password_hasher'
      - '@Eccube\Repository\MemberRepository'
      - '@Eccube\Repository\CategoryRepository'
      - '@Eccube\Repository\CustomerRepository'
      - '@Eccube\Repository\ClassNameRepository'
      - '@Eccube\Repository\ClassCategoryRepository'
      - '@Eccube\Repository\DeliveryDurationRepository'
      - '@Eccube\Repository\DeliveryFeeRepository'
      - '@Eccube\Repository\PaymentRepository'
      - '@Eccube\Repository\PageRepository'
      - '@Eccube\Repository\Master\PrefRepository'
      - '@Eccube\Repository\TagRepository'
      - '@Eccube\Repository\TaxRuleRepository'
      - '@eccube.purchase.flow.order'
      - '@request_stack'
      - 'ja_JP'
    lazy: true
