eccube:
    rate_limiter:
        forgot:
            route: forgot
            method: [ 'POST' ]
            type: ip
            limit: 5
            interval: '30 minutes'
        entry: # 存在しているメールアドレスの確認を防止するためのスロットリング
            route: entry
            method: [ 'POST' ]
            type: ip
            limit: 25
            interval: '30 minutes'
        entry_complete: # 不正な会員登録を防止するためのスロットリング
            route: entry
            method: [ 'POST' ]
            params:
                mode: complete
            type: ip
            limit: 5
            interval: '30 minutes'
        mypage_change:
            route: mypage_change
            method: [ 'POST' ]
            type: user
            limit: 10
            interval: '30 minutes'
        mypage_delivery_new:
            route: mypage_delivery_new
            method: [ 'POST' ]
            type: user
            limit: 10
            interval: '30 minutes'
        mypage_delivery_edit:
            route: mypage_delivery_edit
            method: [ 'POST' ]
            type: user
            limit: 10
            interval: '30 minutes'
        mypage_delivery_delete:
            route: mypage_delivery_delete
            method: [ 'DELETE' ]
            type: user
            limit: 10
            interval: '30 minutes'
        shopping_shipping_multiple_edit_customer:
            route: shopping_shipping_multiple_edit
            method: [ 'POST' ]
            type: user
            limit: 10
            interval: '30 minutes'
        shopping_shipping_edit_customer:
            route: shopping_shipping_edit
            method: [ 'POST' ]
            type: user
            limit: 10
            interval: '30 minutes'
        contact:
            route: contact
            method: [ 'POST' ]
            params:
                mode: complete
            type: ip
            limit: 5
            interval: '30 minutes'
        shopping_confirm_ip:
            route: ~
            limit: 25
            interval: '30 minutes'
        shopping_confirm_customer:
            route: ~
            limit: 10
            interval: '30 minutes'
        shopping_checkout_ip:
            route: ~
            limit: 25
            interval: '30 minutes'
        shopping_checkout_customer:
            route: ~
            limit: 10
            interval: '30 minutes'
        admin_two_factor_auth:
            route: admin_two_factor_auth
            method: [ 'POST' ]
            type: user
            limit: 5
            interval: '30 minutes'
