monolog:
    handlers:
        e_user_deprecated_filter:
            type: filter
            accepted_levels: ['info']
            channels: ['php']
            handler: blackhole
            bubble: false
        main:
            type: fingers_crossed
            action_level: error
            passthru_level: error
            handler: main_rotating_file
        main_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/site.log'
            formatter: eccube.log.formatter.line
            level: debug
        front:
            type: fingers_crossed
            action_level: error
            passthru_level: error
            handler: front_rotating_file
            channels: ['front', 'app', 'php']
        front_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/front.log'
            formatter: eccube.log.formatter.line
            level: error
        admin:
            type: fingers_crossed
            action_level: error
            passthru_level: error
            handler: admin_rotating_file
            channels: ['admin', 'app', 'php']
        admin_rotating_file:
            type: rotating_file
            max_files: 60
            path: '%kernel.logs_dir%/%kernel.environment%/admin.log'
            formatter: eccube.log.formatter.line
            level: error
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine']
        # keep this last
        blackhole:
            type: "null"
