<?php return [
   // duplicated
  'root' => '${ROOT_URLPATH}/',
  'admin_dir' => '${ADMIN_ROUTE}/',
  'tpl' => '${ROOT_PUBLIC_URLPATH}/user_data/packages/default/',
  'admin_tpl' => '${ROOT_PUBLIC_URLPATH}/user_data/packages/admin/',
  'image_path' => '${ROOT_PUBLIC_URLPATH}/upload/save_image/',

  'root_dir' => '${ROOT_DIR}',
  'root_urlpath' => '${ROOT_URLPATH}',
  'template_code' => '${TEMPLATE_CODE}',
  'admin_route' => '${ADMIN_ROUTE}',
  'user_data_route' => '${USER_DATA_ROUTE}',
  'public_path' => '/html',
  'public_path_realdir' => '${ROOT_DIR}/html',
  'image_save_realdir' => '${ROOT_DIR}/html/upload/save_image',
  'image_temp_realdir' => '${ROOT_DIR}/html/upload/temp_image',
  'user_data_realdir' => '${ROOT_DIR}/html/user_data',
  'block_default_realdir' => '${ROOT_DIR}/src/Eccube/Resource/template/default/Block',
  'block_realdir' => '${ROOT_DIR}/app/template/${TEMPLATE_CODE}/Block',
  'template_default_realdir' => '${ROOT_DIR}/src/Eccube/Resource/template/default',
  'template_default_html_realdir' => '${ROOT_DIR}/html/template/default',
  'template_admin_realdir' => '${ROOT_DIR}/src/Eccube/Resource/template/admin',
  'template_admin_html_realdir' => '${ROOT_DIR}/html/template/admin',
  'template_realdir' => '${ROOT_DIR}/app/template/${TEMPLATE_CODE}',
  'template_html_realdir' => '${ROOT_DIR}/html/template/${TEMPLATE_CODE}',
  'template_temp_realdir' => '${ROOT_DIR}/app/cache/eccube/template',
  'csv_temp_realdir' => '${ROOT_DIR}/app/cache/eccube/csv',
  'plugin_realdir' => '${ROOT_DIR}/app/Plugin',
  'plugin_temp_realdir' => '${ROOT_DIR}/app/cache/plugin',
  'plugin_html_realdir' => '${ROOT_DIR}/html/plugin',
  'admin_urlpath' => '${ROOT_PUBLIC_URLPATH}/template/admin',
  'front_urlpath' => '${ROOT_PUBLIC_URLPATH}/template/${TEMPLATE_CODE}',
  'image_save_urlpath' => '${ROOT_PUBLIC_URLPATH}/upload/save_image',
  'image_temp_urlpath' => '${ROOT_PUBLIC_URLPATH}/upload/temp_image',
  'user_data_urlpath' => '${ROOT_PUBLIC_URLPATH}/user_data',
  'plugin_urlpath' => '${ROOT_PUBLIC_URLPATH}/plugin',
];
