name: Apache bench (HTTP load speed) testing for EC-CUBE
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  LoadTest:
    name: Apache bench (HTTP load speed) testing for EC-CUBE
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 4.2
      - name: Setup to EC-CUBE
        run: |
          "docker-compose up -d"
          "docker-compose exec -u www-data ec-cube bin/console eccube:install -n"
        # Home Page Request
      - name: Request home page
        run: |
          "ab -n 100 -c 10 -g https://localhost:8080/"
        # Upload Evidence
      - env:
          GROUP: ${{ matrix.group }}
        if: always()
        run: echo "ARTIFACT_NAME=$(echo ${GROUP} | sed 's,/,-,g')" >> $GITHUB_ENV
      - name: Upload evidence
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ab-${{ env.ARTIFACT_NAME }}-session
          path: ab/test_run
