name: Plugin E2E Test for EC-Cube
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  e2e_plugin_codeception:
    name: Codeception
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: [ 7.4, 8.0, 8.1 ]
        db: [ pgsql10, pgsql14, mysql5, mysql8 ]
        include:
          - db: pgsql10
            database_url: postgres://postgres:password@127.0.0.1:5432/eccube_db
            database_server_version: 10
            database_charset: utf8
          - db: pgsql14
            database_url: postgres://postgres:password@127.0.0.1:5433/eccube_db
            database_server_version: 14
            database_charset: utf8
          - db: mysql5
            database_url: mysql://root:password@127.0.0.1:3306/eccube_db
            database_server_version: 5.7
            database_charset: utf8mb4
          - db: mysql8
            database_url: mysql://root:password@127.0.0.1:3308/eccube_db
            database_server_version: 8
            database_charset: utf8mb4

    services:
      postgres10:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      postgres14:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mysql8:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3308:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mailcatcher:
        image: schickling/mailcatcher
        ports:
          - 1080:1080
          - 1025:1025

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Replace Azure Ubuntu Mirror with Japanese Ubuntu Mirror
        run: |
          sudo sed -i 's/azure\./jp\./' /etc/apt/sources.list
      - name: Set System Locale to Japanese
        run: |
          sudo locale-gen ja_JP.UTF-8
          sudo update-locale LANG=ja_JP.UTF-8
          export LANGUAGE=ja_JP
      - name: Install Japanese language pack
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 3
          command: |
            sudo apt-get update
            sudo apt-get install language-pack-ja-base language-pack-ja
            sudo apt-get install japan*
            sudo apt-get install fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core
      - name: Get base fonts
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: |
            sudo apt-get install ttf-mscorefonts-installer
            sudo fc-cache -fv
      - name: Download all native ECCUBE plugins from latest release
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          run: |
            wget -O ./codeception/_data/recommend.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/Recommend-plugin/releases/latest | grep browser_download_url | cut -d '"' -f 4)
            wget -O ./codeception/_data/coupon.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/coupon-plugin/releases/latest | grep browser_download_url | cut -d '"' -f 4)
            wget -O ./codeception/_data/mail_magazine.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/mail-magazine-plugin/releases/latest | grep browser_download_url | cut -d '"' -f 4)
            wget -O ./codeception/_data/sales.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/sales-report-plugin/releases/latest | grep browser_download_url | cut -d '"' -f 4)
            wget -O ./codeception/_data/related_product.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/related-product-plugin/releases/latest | grep browser_download_url | cut -d '"' -f 4)

            wget -O ./codeception/_data/review.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/ProductReview-plugin/releases/latest | grep browser_download_url | cut -d '"' -f 4)
            wget -O ./codeception/_data/api.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/eccube-api4/releases/latest | grep browser_download_url | cut -d '"' -f 4)

            wget -O ./codeception/_data/maker.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/maker-plugin/releases/latest | grep browser_download_url | cut -d '"' -f 4)
            wget -O ./codeception/_data/product_images.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/ProductImagesUploader/releases/latest | grep browser_download_url | cut -d '"' -f 4)
            wget -O ./codeception/_data/data_migrate.tar.gz $(curl -s https://api.github.com/repos/EC-CUBE/data-migration-plugin/releases/latest | grep browser_download_url | cut -d '"' -f 4)
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: composer install
        run: composer install --dev --no-interaction -o --apcu-autoloader
      - name: Setup to EC-CUBE
        env:
          APP_ENV: 'codeception'
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          DATABASE_CHARSET: ${{ matrix.database_charset }}
        run: |
          echo "APP_ENV=${APP_ENV}" > .env
          echo "TRUSTED_HOSTS=127.0.0.1,localhost" >> .env
          bin/console doctrine:database:create --env=dev
          bin/console doctrine:schema:create --env=dev
          bin/console eccube:fixtures:load --env=dev
      - name: Install ALL ECCUBE Offical Plugins via commandLine
        env:
          APP_ENV: 'codeception'
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          DATABASE_CHARSET: ${{ matrix.database_charset }}
          # bin/console eccube:plugin:install --path=codeception/_data/api.tar.gz
          # bin/console eccube:plugin:install --path=codeception/_data/review.tar.gz --env=dev
        run: |
          bin/console eccube:plugin:install --path=codeception/_data/recommend.tar.gz --env=dev
          bin/console eccube:plugin:install --path=codeception/_data/coupon.tar.gz --env=dev
          bin/console eccube:plugin:install --path=codeception/_data/mail_magazine.tar.gz --env=dev
          bin/console eccube:plugin:install --path=codeception/_data/sales.tar.gz --env=dev
          bin/console eccube:plugin:install --path=codeception/_data/related_product.tar.gz --env=dev

          bin/console eccube:plugin:install --path=codeception/_data/maker.tar.gz --env=dev
          bin/console eccube:plugin:install --path=codeception/_data/product_images.tar.gz --env=dev
      - name: Enable ALL installed official plugins via commandline
        env:
          APP_ENV: 'codeception'
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          DATABASE_CHARSET: ${{ matrix.database_charset }}
          # bin/console eccube:plugin:enable --code=ProductReview42 --env=dev
        run: |
          bin/console eccube:plugin:enable --code=Recommend42 --env=dev
          bin/console eccube:plugin:enable --code=Coupon42 --env=dev
          bin/console eccube:plugin:enable --code=MailMagazine42 --env=dev
          bin/console eccube:plugin:enable --code=SalesReport42 --env=dev
          bin/console eccube:plugin:enable --code=RelatedProduct42 --env=dev

          bin/console eccube:plugin:enable --code=Maker42 --env=dev
          bin/console eccube:plugin:enable --code=ProductImagesUploader42 --env=dev
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@master
      - name: Run Google Chrome in Japanese Language
        run: |
          sed '2 i export LANGUAGE=ja_JP' /opt/google/chrome/google-chrome
      - name: Run chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          echo ">>> Started chrome-driver"
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
      - name: Start PHP Development Server
        env:
          APP_ENV: 'dev'
          XML_OVERRIDE: 't'
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          DATABASE_CHARSET: ${{ matrix.database_charset }}
          MAILER_DSN: 'smtp://127.0.0.1:1025'
          HTTP_SITEURL: 'http://127.0.0.1:7777'
        run: php -S 127.0.0.1:8000 &
      - name: Back up development server (for security plugin check)
        env:
          APP_ENV: 'dev'
          XML_OVERRIDE: 't'
          DATABASE_URL: ${{ matrix.database_url }}
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          DATABASE_CHARSET: ${{ matrix.database_charset }}
          MAILER_DSN: 'smtp://127.0.0.1:1025'
          HTTP_SITEURL: 'http://127.0.0.1:7777'
        run: php -S 127.0.0.1:7777 &
      - name: Start Webhook Development Server
        run: php -S 127.0.0.1:8008 -t codeception/_support/server &
#      - name: Codeception (Run API plugin Installer through e2e test)
#        env:
#          APP_ENV: 'dev'
#          DATABASE_URL: ${{ matrix.database_url }}
#          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
#          DATABASE_CHARSET: ${{ matrix.database_charset }}
#          MAILER_DSN: 'smtp://127.0.0.1:1025'
#          HTTP_SITEURL: 'http://127.0.0.1:7777'
#          GROUP: ${{ matrix.group }}
#          SYMFONY_DEPRECATIONS_HELPER: weak
#        run: vendor/bin/codecept -vvv run acceptance --env chrome,github_action -g install --html install-report.html codeception/acceptance/Plugin/E2E/PL08ApiCest.php
#      - name: Hard reset ALL cache from var/cache after install
#        run: |
#          rm -rf var/cache
#          mkdir var/cache
#          chmod 777 var/cache
#      - name: Codeception (Run Review plugin Installer through e2e test)
#        env:
#          APP_ENV: 'dev'
#          DATABASE_URL: ${{ matrix.database_url }}
#          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
#          DATABASE_CHARSET: ${{ matrix.database_charset }}
#          MAILER_DSN: 'smtp://127.0.0.1:1025'
#          HTTP_SITEURL: 'http://127.0.0.1:7777'
#          GROUP: ${{ matrix.group }}
#          SYMFONY_DEPRECATIONS_HELPER: weak
#        run: vendor/bin/codecept -vvv run acceptance --env chrome,github_action -g install --html install-report.html codeception/acceptance/Plugin/E2E/PL07ProductReviewCest.php
#      - name: Hard reset ALL cache from var/cache after install
#        run: |
#          rm -rf var/cache
#          mkdir var/cache
#          chmod 777 var/cache
#      - name: Codeception (Run Security plugin Installer through e2e test)
#        env:
#          APP_ENV: 'dev'
#          DATABASE_URL: ${{ matrix.database_url }}
#          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
#          DATABASE_CHARSET: ${{ matrix.database_charset }}
#          MAILER_DSN: 'smtp://127.0.0.1:1025'
#          HTTP_SITEURL: 'http://127.0.0.1:7777'
#          GROUP: ${{ matrix.group }}
#          SYMFONY_DEPRECATIONS_HELPER: weak
#        run: vendor/bin/codecept -vvv run acceptance --env chrome,github_action -g install --html install-report.html codeception/acceptance/Plugin/E2E/PL06SecurityCheckCest.php
#      - name: Hard reset ALL cache from var/cache after install
#        run: |
#          rm -rf var/cache
#          mkdir var/cache
#          chmod 777 var/cache
      - name: Codeception (Run priority plugins)
        env:
          APP_ENV: 'dev'
          DATABASE_URL: ${{ matrix.database_url }}
          HTTP_SITEURL: '127.0.0.1:7777'
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          DATABASE_CHARSET: ${{ matrix.database_charset }}
          MAILER_DSN: 'smtp://127.0.0.1:1025'
          GROUP: ${{ matrix.group }}
          DATE_LOCALE: 'en-us'
          SYMFONY_DEPRECATIONS_HELPER: weak
        run: vendor/bin/codecept -vvv run acceptance --env chrome,github_action -g e2e_priority_plugin -x install -x uninstall --html main-report.html codeception/acceptance/Plugin/E2E
      - name: Codeception (Main Process Testing)
        env:
          APP_ENV: 'dev'
          DATABASE_URL: ${{ matrix.database_url }}
          HTTP_SITEURL: '127.0.0.1:7777'
          DATABASE_SERVER_VERSION: ${{ matrix.database_server_version }}
          DATABASE_CHARSET: ${{ matrix.database_charset }}
          MAILER_DSN: 'smtp://127.0.0.1:1025'
          GROUP: ${{ matrix.group }}
          DATE_LOCALE: 'en-us'
          SYMFONY_DEPRECATIONS_HELPER: weak
        run: vendor/bin/codecept -vvv run acceptance --env chrome,github_action -g main -x e2e_priority_plugin --html main-report.html codeception/acceptance/Plugin/E2E
      - name: Upload evidence
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.group }}-evidence
          path: codeception/_output/
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.group }}-logs
          path: var/log/
      - name: Upload webhook logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: codeception-${{ matrix.group }}-webhook-logs
          path: codeception/_support/server/output/
