name: Rector

on:
  workflow_call:

permissions:
  contents: read

jobs:
  rector:
    name: Rector

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1  # v2
        with:
          php-version: '8.1'

      - name: Initialize Composer
        uses: ./.github/actions/composer

      - name: Restore Rector cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5
        with:
          path: var/rector_cache
          key: ${{ runner.os }}-rector-${{ hashFiles('rector.php', 'composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-rector-

      - name: Rector (dry-run)
        run: vendor/bin/rector process --dry-run --ansi --config=rector.php

      - name: Save Rector cache
        if: always()
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7  # v5
        with:
          path: var/rector_cache
          key: ${{ runner.os }}-rector-${{ hashFiles('rector.php', 'composer.lock') }}
