name: Security Access testing for EC-CUBE (Apache)
on:
  pull_request:
  push:
jobs:
  load-test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup to Docker compose
        run: |
          "sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose"
          "sudo chmod +x /usr/local/bin/docker-compose"
      - name: Alter php version to 8.1
        run: |
          "sed -i '1s FROM php:8.1-apache-bullseye' Dockerfile"
        # Home Page Request
      - name: Start EC-CUBE
        run: |
          "docker-compose up -d"
          "docker-compose exec -u www-data ec-cube bin/console eccube:install -n"
      - name: HTTP Request Pages
        run: |
          jq -c '.[]' codeception/workflows/security-access-test/attack_vectors.json | while read i; do
            export ${i} = wget --server-response --spider --quiet http://localhost:8080/${i}
          done
        # Upload Evidence
      - name: Upload evidence
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ab-${{ env.ARTIFACT_NAME }}-session
          path: ab/test_run
