name: Security Access testing for EC-CUBE (Apache)
on:
  pull_request:
  push:
jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: docker build
        run: docker compose build

      - name: Start EC-CUBE
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.mysql.yml up -d

      - name: Run composer
        run: |
          docker-compose exec -T ec-cube composer install --dev --no-interaction -o --apcu-autoloader

      - name: HTTP Request Pages
        run: |
          jq -c '.[]' codeception/workflows/security-access-test/attack_vectors.json | while read i; do
            export ${i} = wget --server-response --spider --quiet http://localhost:8080/${i}
          done
        # Upload Evidence
      - name: Upload evidence
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ab-${{ env.ARTIFACT_NAME }}-session
          path: ab/test_run
