liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%'
                cache_prefix: 'html/upload/cache'
    loaders:
        default:
            filesystem:
                data_root:
                    - '%kernel.project_dir%'
                    - '%kernel.project_dir%/../'
                    - '%kernel.project_dir%/../../'
                    - '%kernel.project_dir%/../../../'
    #    webp:
    #        generate: true
    filter_sets:
        cache: ~
        resize:
