# Read the documentation: https://github.com/suncat2000/MobileDetectBundle/blob/v1.0.5/Resources/doc/index.md
mobile_detect:
#    redirect:
#        full:
#            is_enabled: true
#            host: http://site.com
#            action: redirect
#        mobile:
#            is_enabled: true
#            host: http://m.site.com
#            action: redirect
#        detect_tablet_as_mobile: true
