monolog:
    handlers:
        sentry:
            type: service
            id: Sentry\Monolog\Handler
    channels: ['front', 'admin']

services:
    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }
    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: !php/const Monolog\Logger::ERROR
