services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    # Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\TextExtension: ~

    eccube.twig_sandbox.policy:
        class: Twig\Sandbox\SecurityPolicy
        arguments:
            $allowedTags: "%eccube.twig_sandbox.allowed_tags%"
            $allowedFilters: "%eccube.twig_sandbox.allowed_filters%"
            $allowedFunctions: "%eccube.twig_sandbox.allowed_functions%"
            $allowedMethods: "%eccube.twig_sandbox.allowed_methods%"
            $allowedProperties: "%eccube.twig_sandbox.allowed_properties%"
    eccube.twig_sandbox.extension:
        class: Twig\Extension\SandboxExtension
        arguments:
            - '@eccube.twig_sandbox.policy'
            - false
        tags: ['twig.extension']
    Eccube\Twig\Sandbox\SecurityPolicyDecorator:
        decorates: 'eccube.twig_sandbox.policy'
parameters:
    eccube.twig_sandbox.allowed_tags:
        - 'apply'
        - 'block'
        - 'deprecated'
        - 'embed'
        - 'extends'
        - 'flush'
        - 'for'
        - 'if'
        - 'set'
        - 'spaceless'
        - 'verbatim'
        - 'with'
        - 'form_theme'
        - 'stopwatch'
        - 'trans'
        - 'trans_default_domain'
    eccube.twig_sandbox.allowed_filters:
        - 'abs'
        - 'batch'
        - 'capitalize'
        - 'column'
        - 'convert_encoding'
        - 'country_name'
        - 'currency_name'
        - 'currency_symbol'
        - 'date'
        - 'date_modify'
        - 'default'
        - 'escape'
        - 'first'
        - 'format'
        - 'format_currency'
        - 'format_date'
        - 'format_datetime'
        - 'format_number'
        - 'format_time'
        - 'join'
        - 'json_encode'
        - 'keys'
        - 'language_name'
        - 'last'
        - 'length'
        - 'locale_name'
        - 'lower'
        - 'merge'
        - 'nl2br'
        - 'number_format'
        - 'replace'
        - 'reverse'
        - 'round'
        - 'slice'
        - 'spaceless'
        - 'split'
        - 'striptags'
        - 'timezone_name'
        - 'title'
        - 'trim'
        - 'upper'
        - 'url_encode'
        - 'abbr_class'
        - 'abbr_method'
        - 'file_link'
        - 'file_relative'
        - 'format_args'
        - 'format_args_as_text'
        - 'humanize'
        - 'serialize'
        - 'trans'
        - 'yaml_dump'
        - 'yaml_encode'
        - 'currency_symbol'
        - 'date_day'
        - 'date_day_with_weekday'
        - 'date_format'
        - 'date_min'
        - 'date_sec'
        - 'doctrine_format_sql'
        - 'doctrine_prettify_sql'
        - 'doctrine_pretty_query'
        - 'doctrine_replace_query_parameters'
        - 'e'
        - 'ellipsis'
        - 'file_ext_icon'
        - 'form_encode_currency'
        - 'format_*_number'
        - 'format_log_message'
        - 'no_image_product'
        - 'price'
        - 'purify'
        - 'time_ago'
    eccube.twig_sandbox.allowed_functions:
        - 'cycle'
        - 'date'
        - 'max'
        - 'min'
        - 'random'
        - 'range'
        - 'country_timezones'
        - 'absolute_url'
        - 'asset'
        - 'asset_version'
        - 'csrf_token'
        - 'form_parent'
        - 'fragment_uri'
        - 'impersonation_exit_path'
        - 'impersonation_exit_url'
        - 'is_granted'
        - 'logout_path'
        - 'logout_url'
        - 'path'
        - 'relative_path'
        - 't'
        - 'url'
        - 'active_menus'
        - 'class_categories_as_json'
        - 'country_names'
        - 'csrf_token_for_anchor'
        - 'currency_names'
        - 'currency_symbol'
        - 'field_choices'
        - 'field_errors'
        - 'field_help'
        - 'field_label'
        - 'field_name'
        - 'field_value'
        - 'get_all_carts'
        - 'get_cart'
        - 'get_carts_total_price'
        - 'get_carts_total_quantity'
        - 'has_errors'
        - 'is_reduced_tax_rate'
        - 'language_names'
        - 'product'
        - 'workflow_can'
        - 'workflow_has_marked_place'
        - 'workflow_marked_places'
        - 'workflow_metadata'
        - 'workflow_transition'
        - 'workflow_transition_blockers'
        - 'workflow_transitions'
    eccube.twig_sandbox.allowed_methods:
        'Symfony\Bridge\Twig\AppVariable': [ 'getrequest' ]
        'Symfony\Component\HttpFoundation\Request': [ 'geturi' ]
    eccube.twig_sandbox.allowed_properties: []