services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #Twig\Extensions\ArrayExtension: ~
    #Twig\Extensions\DateExtension: ~
    Twig\Extensions\IntlExtension: ~
    #Twig\Extensions\TextExtension: ~

    eccube.twig_sandbox.policy:
        class: Twig\Sandbox\SecurityPolicy
        arguments:
            $allowedTags: "%eccube.twig_sandbox.allowed_tags%"
            $allowedFilters: "%eccube.twig_sandbox.allowed_filters%"
            $allowedFunctions: "%eccube.twig_sandbox.allowed_functions%"
            $allowedMethods: "%eccube.twig_sandbox.allowed_methods%"
            $allowedProperties: "%eccube.twig_sandbox.allowed_properties%"
    eccube.twig_sandbox.extension:
        class: Twig\Extension\SandboxExtension
        arguments:
            - '@eccube.twig_sandbox.policy'
            - false
        tags: ['twig.extension']
    Eccube\Twig\Sandbox\SecurityPolicyDecorator:
        decorates: 'eccube.twig_sandbox.policy'
parameters:
    eccube.twig_sandbox.allowed_tags:
        - 'apply'
        - 'block'
        - 'deprecated'
        - 'embed'
        - 'extends'
        - 'flush'
        - 'for'
        - 'if'
        - 'set'
        - 'spaceless'
        - 'verbatim'
        - 'with'
        - 'form_theme'
        - 'stopwatch'
        - 'trans'
        - 'trans_default_domain'
    eccube.twig_sandbox.allowed_filters:
        - 'abs'
        - 'batch'
        - 'capitalize'
        - 'column'
        - 'convert_encoding'
        - 'date'
        - 'date_modify'
        - 'default'
        - 'escape'
        - 'first'
        - 'format'
        - 'join'
        - 'json_encode'
        - 'keys'
        - 'last'
        - 'length'
        - 'lower'
        - 'merge'
        - 'nl2br'
        - 'number_format'
        - 'replace'
        - 'reverse'
        - 'round'
        - 'slice'
        - 'spaceless'
        - 'split'
        - 'striptags'
        - 'title'
        - 'trim'
        - 'upper'
        - 'url_encode'
        - 'abbr_class'
        - 'abbr_method'
        - 'file_link'
        - 'format_args'
        - 'format_args_as_text'
        - 'humanize'
        - 'trans'
        - 'yaml_dump'
        - 'yaml_encode'
        - 'date_day'
        - 'date_day_with_weekday'
        - 'date_format'
        - 'date_min'
        - 'date_sec'
        - 'doctrine_pretty_query'
        - 'doctrine_replace_query_parameters'
        - 'e'
        - 'ellipsis'
        - 'file_ext_icon'
        - 'form_encode_currency'
        - 'format_log_message'
        - 'no_image_product'
        - 'price'
        - 'time_ago'
        - 'doctrine_minify_query'
        - 'localizedcurrency'
        - 'localizeddate'
        - 'localizednumber'
        - 'transchoice'
    eccube.twig_sandbox.allowed_functions:
        - 'cycle'
        - 'date'
        - 'max'
        - 'min'
        - 'random'
        - 'range'
        - 'absolute_url'
        - 'asset'
        - 'asset_version'
        - 'csrf_token'
        - 'is_granted'
        - 'logout_path'
        - 'logout_url'
        - 'path'
        - 'relative_path'
        - 'url'
        - 'active_menus'
        - 'class_categories_as_json'
        - 'csrf_token_for_anchor'
        - 'currency_symbol'
        - 'get_all_carts'
        - 'get_cart'
        - 'get_carts_total_price'
        - 'get_carts_total_quantity'
        - 'has_errors'
        - 'is_reduced_tax_rate'
        - 'product'
        - 'workflow_can'
        - 'workflow_has_marked_place'
        - 'workflow_marked_places'
        - 'workflow_transitions'
        - 'device_version'
        - 'full_view_url'
        - 'is_android_os'
        - 'is_device'
        - 'is_full_view'
        - 'is_ios'
        - 'is_mobile'
        - 'is_mobile_view'
        - 'is_not_mobile_view'
        - 'is_tablet'
        - 'is_tablet_view'
    eccube.twig_sandbox.allowed_methods:
        'Symfony\Bridge\Twig\AppVariable': [ 'getrequest' ]
        'Symfony\Component\HttpFoundation\Request': [ 'geturi' ]
    eccube.twig_sandbox.allowed_properties: []
